name: API Automation with Allure

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Api-test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev #install allure

      - name: Build with Gradle
        run:
            chmod +x ./gradlew #make gradlew executable
            ./gradlew build #Run the build task before test

      - name: Run API tests
        run: ./gradlew clean test

      - name: Generate Allure Report
        run:  .allure generate build/allure-results -o allure-report --clean

      # Deploy to GitHub Pages
      - name: Deploy to GitHub  Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
           personal_token : ${{ secrets.PERSONAL_TOKEN }}
           publish_dir: allure-report #html yang publish
