name: API Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  api-automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Set executable gradlew
      - name: Setup gradlew
        working-directory: ./OtomasiAPI
        run: chmod +x gradlew

      # 4. Run Cucumber Tests
      - name: Run API Cucumber Tests
        working-directory: ./OtomasiAPI
        run: ./gradlew clean test cucumber

      # 5. Prepare HTML report
      - name: Prepare Cucumber Report
        run: |
          cp OtomasiAPI/build/cucumber-report/cucumber.html OtomasiAPI/build/cucumber-report/index.html

      # 6. Upload report artifact
      - name: Upload Cucumber Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-api-report
          path: OtomasiAPI/build/cucumber-report

      # 7. Deploy report to GitHub Pages
      - name: Deploy Cucumber Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./OtomasiAPI/build/cucumber-report
          publish_branch: gh-pages

      # 8. Add report link to workflow summary
      - name: Add Cucumber Report link to Summary
        run: |
          echo "### ðŸ¥’ Reqres User API Test Result" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: GitHub Actions" >> $GITHUB_STEP_SUMMARY
          echo "- Report Type: Cucumber HTML Report" >> $GITHUB_STEP_SUMMARY
          echo "- Report URL: https://${{ github.r
