name: API Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  api-automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradlew
        working-directory: ./OtomasiAPI
        run: chmod +x gradlew

      - name: Create report folder
        run: mkdir -p OtomasiAPI/build/cucumber-report

      - name: Run API Cucumber Tests
        working-directory: ./OtomasiAPI
        run: ./gradlew clean cucumber

      - name: Prepare Cucumber Report
        run: |
          if [ -f OtomasiAPI/build/cucumber-report/cucumber.html ]; then
            cp OtomasiAPI/build/cucumber-report/cucumber.html OtomasiAPI/build/cucumber-report/index.html
          else
            echo "cucumber.html not found. Skipping copy."
          fi

      - name: Upload Cucumber Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-api-report
          path: OtomasiAPI/build/cucumber-report
          if-no-files-found: warn

      - name: Deploy Cucumber Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./OtomasiAPI/build/cucumber-report
          publish_branch: gh-pages

      - name: Add Cucumber Report link to Summary
        run: |
          echo "### ðŸ¥’ Reqres User API Test Result" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: GitHub Actions" >> $GITHUB_STEP_SUMMARY
          echo "- Report Type: Cucumber HTML Report" >> $GITHUB_STEP_SUMMARY
          echo "- Report URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY
