name: Web Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  automation:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    #download repo
    steps:
    - uses: actions/checkout@v4
    #setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    #install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v2.1.0
    #setup Gradlew
    - name: Setup gradlew
      run: chmod +x gradlew
    #Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew cucumber
    
  


    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
